### ISSUE TITLE
ok pattern

### ISSUE THREAD

**Issue by 1995parham** [blizzy78/varnamelen#1]
There are cases like:

```go
id, ok := claims["user_id"].(int)
if !ok {
}
```
which `ok` is a known pattern.

**Comment by blizzy78** [comment]
Good point. I've just added the `-ignoreTypeAssertOk` flag that will allow to ignore `ok` variables that hold the bool return value of a type assertion.

I will also add similar flags for the bool return values of channel read and map access.

**Comment by 1995parham** [comment]
Thank you for your attention and work :+1:
