### ISSUE TITLE
http handler context

### ISSUE THREAD

**Issue by 1995parham** [blizzy78/varnamelen#2]
some HTTP frameworks like [echo](github.com/labstack/echo) have context which is different from go context and sometimes we need to have them both so using the variable name `c` is a pattern for them.

```go
// e.GET("/users/:id", getUser)
func getUser(c echo.Context) error {
  	// User ID from path `users/:id`
  	id := c.Param("id")
	return c.String(http.StatusOK, id)
}
```

I don't know how, but it would be great if we can consider this for popular frameworks.

**Comment by blizzy78** [comment]
We already have the `-ignoreNames` flag, but I don't think for cases like this it's not quite enough. It would be better to have a new flag that also allows to specify the exact type of the variable to ignore.

**Comment by blizzy78** [comment]
I've added the `-ignoreDecls` flag that allows to ignore arbitrary variable declarations, for example:

```
-ignoreDecls 'c echo.Context, f *foo.Bar, t testing.T'
```

**Comment by blizzy78** [comment]
varnamelen 0.6.0 can now infer types of expressions. For example, for a statement like this

```go
c := context.Background()
```

it is now able to infer the type of `c`.
