### ISSUE TITLE
too short variables in constuctor

### ISSUE THREAD

**Issue by maranqz** [blizzy78/varnamelen#22]
Hello. My structure initializing in constructor with options is marked as "too short".

What do you think about option to skip this case.

```
struct st {
  p1 bool
  p2 bool
  ....
}

type Option func(*st)

func New() st {
   s := st{
     // set default values
   }

   for _, o := range oo {
      o(&s)
   }

   return s
}
```

**Comment by blizzy78** [comment]
In this case, a comment `//nolint:varnamelen` should be used.
