### ISSUE TITLE
Support ignoring const declarations

### ISSUE THREAD

**Issue by Seirdy** [blizzy78/varnamelen#4]
Constants such as physical values or well-known parameters of mathematical functions may have short names; however, the `ignore-decls` configs don't allow specifying allowed const declarations.

A code excerpt from one of my projects:

``` go
const (
	// C is the speed of light in a vacuum, m/s.
	C = 299792458
	// G is the gravitation constant, m^3/kg/s^2.
	G = 6.67408e-11
	// ...
)
```

As long as varnamelen checks constants, it should be possible to ignore them just like variables.

**Comment by blizzy78** [comment]
The `-ignoreDecls` flag will now allow constant declarations in the form of `const <name>`.
